### ISSUE TITLE
bug in subview

### ISSUE THREAD

**Issue by Alex-Markham** [marrlab/causalspyne#16]
randomly got an error in [this run](https://github.com/marrlab/causalspyne/actions/runs/11147098789/job/30980580291), though most runs don't result in an error

**Comment by Alex-Markham** [comment]
maybe addressing #5 fixes this?

**Comment by smilesun** [comment]
yes, we have to think an algorithm then to fix #5

**Comment by smilesun** [comment]
https://github.com/marrlab/causalspyne/issues/21
