### ISSUE TITLE
ensure/enforce unobserved confounder which is child of observables

### ISSUE THREAD

**Issue by smilesun** [marrlab/causalspyne#5]
currently, we have https://github.com/marrlab/causalspyne/blob/f1a2a07e6d90ae3ca5eca1ba6819f6d2b3905946/causalspyne/dag_gen.py#L66 
to make sure that we have confounder in the DAG, after num_nodes number of trials. 

Then 

we have [0.5, 0.9] as percentile of coufounders to hide, the higher the number, the more likely that the coufounder we hide will be child of observables. 
```

gen_partially_observed(size_micro_node_dag=4,
                       num_macro_nodes=4,
                       degree=2,  # average vertex/node degree
                       list_confounder2hide=[0.5, 0.9], # choie of confounder to hide: percentile or index of all toplogically sorted confounders
                       num_sample=200,
                       output_dir="output")
```

how to ensure that if we call the above function, the DAG has confounder which is child of observable?

**Comment by smilesun** [comment]
```
causalspyne/dag_gen.py
6:import warnings
77:                warnings.warn(

causalspyne/dag_viewer.py
5:import warnings
77:            warnings.warn(
143:            warnings.warn("no subview of DAG available, exit now!")
190:            warnings.warn("no subview of DAG available")

```

**Comment by smilesun** [comment]
So my guess is as long we are enforced enough confounders, then hiding the topologically low ranked confounders will enforce confounders being child of observable

**Comment by Alex-Markham** [comment]
Yes, that should work on average. But what about instead, when we randomly select the confounders, we only choose from nodes that have at least 1 parent. This should be guaranteed to confound in the way we want, shouldn't it? Maybe also ensure at least 1 child, since marginalizing sink nodes, since hiding a sink node doesn't affect the rest of the graph

**Comment by smilesun** [comment]
these two pr fixed the problem,
 
first pr added enough confounders
second pr refines the code

[smilesun](https://github.com/marrlab/causalspyne/commits?author=smilesun)
[Merge pull request](https://github.com/marrlab/causalspyne/commit/1304ca74a9d18dfefecbbaa6820eaf2132c58449) https://github.com/marrlab/causalspyne/pull/23 [from marrlab/force_confounder](https://github.com/marrlab/causalspyne/commit/1304ca74a9d18dfefecbbaa6820eaf2132c58449)
[1304ca7](https://github.com/marrlab/causalspyne/commit/1304ca74a9d18dfefecbbaa6820eaf2132c58449)
 · 
3 hours ago
History



[Merge pull request](https://github.com/marrlab/causalspyne/commit/b6a1fc994f84642f9ff075eab136ce77fef828e0) https://github.com/marrlab/causalspyne/pull/24 [from marrlab/extra_confounder_graphviz](https://github.com/marrlab/causalspyne/commit/b6a1fc994f84642f9ff075eab136ce77fef828e0)
[b6a1fc9](https://github.com/marrlab/causalspyne/commit/b6a1fc994f84642f9ff075eab136ce77fef828e0)
 · 
now
History
